#ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#obj-$(CONFIG_MTK_MC34XX) := mc34xx.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
#ccflags-y += -w

#obj-y	:=  mc3410-i2c.o
obj-$(CONFIG_MTK_MC34XX) := mc34xx.o